### ISSUE TITLE
ImportError: cannot import name 'passwd' from 'IPython.lib' when using pytorch1.12.1-cuda11.6

### ISSUE THREAD

**Issue by abdksyed** [rlan/notebooks#112]
I pulled the pytorch1.12.1-cuda11.6 image and ran the docker run command. The jupyter server config file is giving an exception.

```
[E 10:04:44.184 NotebookApp] Exception while loading config file /root/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 844, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 625, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 658, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)
      File "/root/.jupyter/jupyter_notebook_config.py", line 2, in <module>
        from IPython.lib import passwd
    ImportError: cannot import name 'passwd' from 'IPython.lib' (/usr/local/lib/python3.8/dist-packages/IPython/lib/__init__.py)
[I 10:04:44.224 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
```

The server is running on localhost 8888, but when opening in browser after mapping the port to local 8888, the server is not opening.

**Comment by rlan** [comment]
@abdksyed Thank you for reporting this issue. I am able to duplicate your error message. Fixing now.

**Comment by rlan** [comment]
It looks how jupyter does init configuration has changed.
@abdksyed A work-around is to use the PyTorch 1.10.0 series. They don't have the error. Tags `pytorch1.10.0` or `pytorch1.10.0-cuda11.3.1` or `pytorch1.10.0-cuda10.2`.

**Comment by rlan** [comment]
Fixed versions have been pushed to docker hub. Please pull to update your local copy:

```sh
docker pull wqael/notebooks:pytorch1.12.1
```

```sh
docker pull wqael/notebooks:pytorch1.12.1-cuda11.6
```

```sh
docker pull wqael/notebooks:pytorch1.12.1-cuda11.3.1
```

```sh
docker pull wqael/notebooks:pytorch1.12.1-cuda10.2
```
