### ISSUE TITLE
Tornado server can't bind to port

### ISSUE THREAD

**Issue by kunaltyagi** [rlan/notebooks#57]
```py
$ nvidia-docker run --gpus=all -e HOME=/project -v "$PWD:/project" -it --rm wqael/notebooks:jupyter-keras-tf1.12.3-py3-cuda9
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1408, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

`tensorflow/tensorflow:latest-gpu-jupyter` works normally

**Comment by rlan** [comment]
Hey man! Thanks for reporting this. It looks like an upstream problem. If I use the official image which mine is a child, I get different error messages than you but jupyter won't start like you.

```
$ nvidia-docker run -e HOME=/project -v "$PWD:/project" -it --rm tensorflow/tensorflow:1.12.3-gpu-py3
Unable to find image 'tensorflow/tensorflow:1.12.3-gpu-py3' locally
1.12.3-gpu-py3: Pulling from tensorflow/tensorflow
18d680d61657: Already exists
0addb6fece63: Already exists
78e58219b215: Already exists
eb6959a66df2: Already exists
e3eb30fe4844: Already exists
852c9b7a4425: Already exists
0a298bf31111: Already exists
f43ecd71dda8: Already exists
9f554feaeba1: Already exists
abf1fc85d970: Already exists
3e67c4ad17bb: Already exists
c60e8159f45c: Already exists
2b01db739666: Already exists
1553de0cb9ac: Already exists
1ed5c01b0218: Already exists
9913722703a5: Already exists
442335dc9a85: Already exists
11581f4cac53: Already exists
Digest: sha256:13ff258e70712cdbbbc303d27aeab8ad815c265e0e35134a27fd988b3007fd14
Status: Downloaded newer image for tensorflow/tensorflow:1.12.3-gpu-py3
[I 08:36:06.905 NotebookApp] Writing notebook server cookie secret to /project/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1408, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

```

There is a workaround: don't remap the home.

```
$ nvidia-docker run -v "$PWD:/project" -it --rm wqael/notebooks:jupyter-keras-tf1.12.3-py3-cuda9
[I 08:41:19.582 NotebookApp] JupyterLab extension loaded from /usr/local/lib/python3.5/dist-packages/jupyterlab
[I 08:41:19.582 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 08:41:19.585 NotebookApp] Serving notebooks from local directory: /notebooks
[I 08:41:19.586 NotebookApp] The Jupyter Notebook is running at:
[I 08:41:19.586 NotebookApp] http://(b2dedb1d0c33 or 127.0.0.1):8888/?token=dabb7a24ce51b8001b180ec87c9d7437353a1a4f332897b3
[I 08:41:19.586 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:41:19.587 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(b2dedb1d0c33 or 127.0.0.1):8888/?token=dabb7a24ce51b8001b180ec87c9d7437353a1a4f332897b3
^C[I 08:41:24.370 NotebookApp] interrupted
Serving notebooks from local directory: /notebooks
0 active kernels
The Jupyter Notebook is running at:
http://(b2dedb1d0c33 or 127.0.0.1):8888/?token=dabb7a24ce51b8001b180ec87c9d7437353a1a4f332897b3
Shutdown this notebook server (y/[n])? ^C[C 08:41:28.117 NotebookApp] received signal 2, stopping
[I 08:41:28.119 NotebookApp] Shutting down 0 kernels
```

I think I saw somewhere sometime ago that jupyter configuration (eg port to listen to) is done at the home folder with a file. That could be the problem here.

**Comment by kunaltyagi** [comment]
> There is a workaround: don't remap the home.

Got it. Thanks :)
